data:
    minerooms:
        load:
            options:
            - "chat:"
            - "    message: \"<<arg0>> <arg1>\""
            - "levels:"
            - "    -1: \"<lang:minerooms.command.noClip.levels.-1>\""
            - "    0: \"<lang:minerooms.command.noClip.levels.0>\""
            - "    1: \"<lang:minerooms.command.noClip.levels.1>\""
            - "    2: \"<lang:minerooms.command.noClip.levels.2>\""
            - "    3: \"<lang:minerooms.command.noClip.levels.3>\""
            - "    4: \"<lang:minerooms.command.noClip.levels.4>\""
            - "    5: \"<lang:minerooms.command.noClip.levels.5>\""
            - "    99: \"<lang:minerooms.command.noClip.levels.99>\""
            - "ranks:"
            - "    default:"
            - "        name: \"<lang:minerooms.ranks.default.name>\""
            - "        perms:"
            - "            - void"
            - "    wanderer:"
            - "        name: \"<lang:minerooms.ranks.wanderer.name>\""
            - "        perms:"
            - "            - server.send_message"
            - "            - item.drop"
            - "            - item.pickup"
            - "            - player.move"
            - "            - player.craft"
            - "            - server.command"
            - "            - server.command.tell"
            - "            - server.command.teammsg"
            - "            - server.command.tm"
            - "            - server.command.me"
            - "            - server.command.minerooms"
            - "    meg_member:"
            - "        name: \"<lang:minerooms.ranks.meg_member.name>\""
            - "        perms:"
            - "            - permissions.wanderer"
            - "    moderator:"
            - "        name: \"<lang:minerooms.ranks.moderator.name>\""
            - "        perms:"
            - "            - permissions.wanderer"
            - "            - permissions.meg_member"
            - "    administrator:"
            - "        name: \"<lang:minerooms.ranks.administrator.name>\""
            - "        perms:"
            - "            - permissions.wanderer"
            - "            - permissions.meg_member"
            - "            - permissions.moderator"
            - "            - op"