data:
    minerooms:
        load:
            options:
            - "ranks:"
            - "    default: randomGuy"
            - "    wanderer:"
            - "        name: \"<lang:minerooms.ranks.wanderer.name>\""
            - "        perms:"
            - "            - server.send_message"
            - "            - item.drop"
            - "            - item.pickup"
            - "            - player.move"
            - "            - player.craft"
            - "            - server.command"
            - "            - server.command.tell"
            - "            - server.command.teammsg"
            - "            - server.command.tm"
            - "            - server.command.me"
            - "            - server.command.minerooms"
            - "    moderator:"
            - "        name: \"<lang:minerooms.ranks.moderator.name>\""
            - "        perms:"
            - "            - permissions.wanderer"
            - "    administrator:"
            - "        name: \"<lang:minerooms.ranks.administrator.name>\""
            - "        perms:"
            - "            - op"