data:
    minerooms:
        load:
            options:
            - "chat:"
            - "    message: \"<<arg0>> <arg1>\""
            - "levels:"
            - "    -1:"
            - "        name: \"<lang:minerooms.command.noClip.levels.-1>\""
            - "        survival_difficulty: 0"
            - "        secure: true"
            - "        stable: true"
            - "        entity: 0"
            - "        pvp: false"
            - "    0:"
            - "        name: \"<lang:minerooms.command.noClip.levels.0>\""
            - "        survival_difficulty: 1"
            - "        secure: true"
            - "        stable: false"
            - "        entity: 0"
            - "        pvp: false"
            - "    1:"
            - "        name: \"<lang:minerooms.command.noClip.levels.1>\""
            - "        survival_difficulty: 1"
            - "        secure: true"
            - "        stable: true"
            - "        entity: 1"
            - "        pvp: false"
            - "    2:"
            - "        name: \"<lang:minerooms.command.noClip.levels.2>\""
            - "        survival_difficulty: 2"
            - "        secure: false"
            - "        stable: true"
            - "        entity: 2"
            - "        pvp: false"
            - "    3:"
            - "        name: \"<lang:minerooms.command.noClip.levels.3>\""
            - "        survival_difficulty: 4"
            - "        secure: false"
            - "        stable: false"
            - "        entity: 3"
            - "        pvp: true"
            - "    4:"
            - "        name: \"<lang:minerooms.command.noClip.levels.4>\""
            - "        survival_difficulty: 1"
            - "        secure: true"
            - "        stable: true"
            - "        entity: 1"
            - "        pvp: false"
            - "    5:"
            - "        name: \"<lang:minerooms.command.noClip.levels.5>\""
            - "        survival_difficulty: 2"
            - "        secure: false"
            - "        stable: true"
            - "        entity: 2"
            - "        pvp: false"
            - "    99:"
            - "        name: \"<lang:minerooms.command.noClip.levels.99>\""
            - "        survival_difficulty: 5"
            - "        secure: true"
            - "        stable: true"
            - "        entity: 0"
            - "        pvp: false"
            - "    666:"
            - "        name: \"<lang:minerooms.command.noClip.levels.666>\""
            - "        survival_difficulty: 5"
            - "        secure: false"
            - "        stable: false"
            - "        entity: 5"
            - "        pvp: true"
            - "restock:"
            - "    default:"
            - "        iron_ingot:"
            - "            min: 1"
            - "            max: 5"
            - "            chance: 100"
            - "            custom:"
            - "                name: \"BIG\""
            - "                lores:"
            - "                    - "
            - "        stick:"
            - "            min: 1"
            - "            max: 3"
            - "            chance: 100"
            - "            custom:"
            - "                name: \"STICK OF GOD\""
            - "                lores:"
            - "                    - <lang:minerooms.command.noClip.levels.-1>"
            - "    rare:"
            - "        golden_apple:"
            - "            min: 0"
            - "            max: 3"
            - "            chance: 50"
            - "            custom:"
            - "                name: \"Pomme de L'amour\""
            - "                lores:"
            - "                    - "
            - "        carrot:"
            - "            min: 0"
            - "            max: 2"
            - "            chance: 50"
            - "            custom:"
            - "                name: \"Carrote de dieu\""
            - "                lores:"
            - "                    - §eOh petit coquin"
            - "ranks:"
            - "    default:"
            - "        name: \"<lang:minerooms.ranks.default.name>\""
            - "        perms:"
            - "            - void"
            - "    wanderer:"
            - "        name: \"<lang:minerooms.ranks.wanderer.name>\""
            - "        perms:"
            - "            - server.send_message"
            - "            - item.drop"
            - "            - item.pickup"
            - "            - player.move"
            - "            - player.craft"
            - "            - server.command"
            - "            - server.command.tell"
            - "            - server.command.teammsg"
            - "            - server.command.tm"
            - "            - server.command.me"
            - "            - server.command.minerooms"
            - "            - server.command.language"
            - "    meg_member:"
            - "        name: \"<lang:minerooms.ranks.meg_member.name>\""
            - "        perms:"
            - "            - permissions.wanderer"
            - "    moderator:"
            - "        name: \"<lang:minerooms.ranks.moderator.name>\""
            - "        perms:"
            - "            - permissions.wanderer"
            - "            - permissions.meg_member"
            - "            - server.command.ban"
            - "            - server.command.kick"
            - "            - server.command.mute"
            - "    administrator:"
            - "        name: \"<lang:minerooms.ranks.administrator.name>\""
            - "        perms:"
            - "            - permissions.wanderer"
            - "            - permissions.meg_member"
            - "            - permissions.moderator"
            - "            - op"